name: Clang Formatter
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Formatting files
        run: find ./project/discord-rpc -name '*.cpp' -o -name '*.m' -o -name '*.h' | xargs clang-format -i

      - name: Verify Formatting
        run: git status --short

      - name: Push formatted files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git diff --quiet || git commit -m "Apply clang-format changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
