name: Testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Compiling 
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxdiscord_rpc .
          cd sample
          haxe build.hxml
